### PR TITLE
Move GPL copyright statement to the README

### PR DESCRIPTION
**Pull request by fmarier**
I noticed that the copy of the GPL has been modified. There are two problems with this:

- it's in the section that is designed for other people to copy paste into their code (so they could accidentally end up with Michael Altfield in their programs
- the FSF doesn't allow modification of the license text unless the name of the license is changed too

The right place to put that copyright statement is somewhere like the README. Not sure whether that's exactly how you want it, but here's a suggestion of how to do it.

### CODE REVIEW

**Comment by maltfield** [comment]
Thanks! Looks like my "malicous unicode detection" checks had an error when running :(

 * https://tech.michaelaltfield.net/2021/11/22/bidi-unicode-github-defense/

I manually verified that, in fact, there are no (malicious) unicode characters in this PR's commits's diff

```
user@disp9079:~$ git clone https://github.com/fmarier/buskill-app.git
Cloning into 'buskill-app'...
remote: Enumerating objects: 5240, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (34/34), done.
Receiving objects:  21% (1144/5240), 166.83 MiB | 365.00 KiB/s
remote: Total 5240 (delta 45), reused 69 (delta 42), pack-reused 5164
Receiving objects: 100% (5240/5240), 194.06 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (2837/2837), done.
user@disp9079:~$ 

user@disp9079:~$ cd buskill-app/
user@disp9079:~/buskill-app$ 

user@disp9079:~/buskill-app$ git checkout -b dev
Switched to a new branch 'dev'
user@disp9079:~/buskill-app$ 

user@disp9079:~/buskill-app$ git checkout -b fmarier-fix-gpl-copyright-statement dev
Switched to a new branch 'fmarier-fix-gpl-copyright-statement'
user@disp9079:~/buskill-app$ 

user@disp9079:~/buskill-app$ git pull https://github.com/fmarier/buskill-app.git fix-gpl-copyright-statement
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/fmarier/buskill-app
 * branch            fix-gpl-copyright-statement -> FETCH_HEAD
Updating b712e4c..1c7a550
Fast-forward
 LICENSE                                          |   6 +-
 README.md                                        |  31 ++++--
 docs/attribution.rst                             |   2 +
 docs/buildManpage.sh                             |  61 +++++++++++
 docs/images/buskill_explainer_video_20211210.gif | Bin 0 -> 5007843 bytes
 docs/software_dev/depends.rst                    |  94 +++++++++++++++++
 docs/software_dev/index.rst                      |   2 +
 docs/software_dev/release.rst                    |  20 +++-
 docs/software_dev/test.rst                       | 126 +++++++++++++++++++++++
 docs/software_usr/manpage.rst                    |  78 ++++++++++++++
 src/packages/buskill/root_child_mac.py           |   2 +-
 11 files changed, 408 insertions(+), 14 deletions(-)
 create mode 100755 docs/buildManpage.sh
 create mode 100644 docs/images/buskill_explainer_video_20211210.gif
 create mode 100644 docs/software_dev/depends.rst
 create mode 100644 docs/software_dev/test.rst
 create mode 100644 docs/software_usr/manpage.rst
user@disp9079:~/buskill-app$

user@disp9079:~/buskill-app$ git diff --unified=0  b7c09ec861eab4fb8508c9d022c4a250277811a8 | grep -oP "[^\x00-\x7F]*"
user@disp9079:~/buskill-app$ echo $?
0
user@disp9079:~/buskill-app$ git diff --unified=0  b7c09ec861eab4fb8508c9d022c4a250277811a8 | grep -oP "[^\x00-\x7F]*" | hd
user@disp9079:~/buskill-app$ 
```

**Comment by maltfield** [comment]
Sorry, I'm a dummy. I honestly thought I was *supposed* to replace the the things in the angle brackets with my software. Thanks for pointing that out and helping to correct it!

I merged this into `dev` and just made a few follow-up changes to README. Hopefully we're all GNU compliant now. If now, please let me know.

**Comment by fmarier** [comment]
> Thanks! Looks like my "malicous unicode detection" checks had an error when running :(

Ah, what was the error? Was there a bad character somewhere in the README?

**Comment by maltfield** [comment]
Nah, your commit is fine. It's my checker that's broken.

```
 RequestError [HttpError]: Resource not accessible by integration
    at /__w/_actions/actions/github-script/v5/dist/index.js:4561:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/BusKill/buskill-app/issues/51/comments',
    status: 403,
```

idk, code rot probably due to GitHub API breaking changes 🤷

**Pull request merged**
