### PR TITLE
Optimize images losslessly

### PR DESCRIPTION
**Pull request by fmarier**
This is the result of running the following commands on the PNGs:

```
pngcrush -q -rem gAMA -rem alla -rem text
optipng -o9
advpng -z -4
```
using [this script](https://github.com/fmarier/user-scripts/blob/master/optimize_images).

### CODE REVIEW

**Comment by maltfield** [comment]
Thanks for the PR!

Because:

1. Images are binaries,
2. There have been numerous vulnerabilities spread through specially-crafted, malicious image historically,
3. It's not trivial to verify the banality of a binary, and
4. I can't prove a negative

...I'm not going to merge this, **but** I will manually execute your user script on my end and push that up.

**Comment by fmarier** [comment]
Since I submitted this PR, I found an even better tool for this (https://github.com/fmarier/user-scripts/blob/master/apply-zopflipng). The script I linked above is already updated though.

It will take longer to run, but it will shrink the images further.

**Comment by maltfield** [comment]
and all of these commands can be run over-and-over without ever causing degradation in quality?

**Comment by fmarier** [comment]
Yes, they are loss-less as far as the pixels are concerned. Though it does remove the EXIF tags on JPEGs for example, so it's not loss-less as far as the bytes are concerned :)

**Comment by maltfield** [comment]
This has been done in https://github.com/BusKill/buskill-app/issues/81

**Pull request closed without merging**
